/**:
  controller_manager:
    ros__parameters:
      update_rate: 100

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      drive_controller:
        type: diff_drive_controller/DiffDriveController
      imu_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster

  # IMU specification: https://www.phidgets.com/?tier=3&catid=10&pcid=8&prodid=1025#Tab_Specifications
  imu_broadcaster:
    ros__parameters:
      sensor_name: <namespace>/imu
      frame_id: <namespace>/imu_link
      # orientation_stddev: 4.3e-2 rad determined experimentally
      static_covariance_orientation: [1.8e-3, 0.0, 0.0, 0.0, 1.8e-3, 0.0, 0.0, 0.0, 1.8e-3]
      # angular_velocity_stdev: 0.59 deg/s (0.01 rad/s) gyroscope white noise sigma, according to the manual
      static_covariance_angular_velocity: [1.0e-4, 0.0, 0.0, 0.0, 1.0e-4, 0.0, 0.0, 0.0, 1.0e-4]
      # linear_acceleration_stdev: 2.8 mg (0.0275 m/s^2) accelerometer white noise sigma, according to the manual
      static_covariance_linear_acceleration: [7.6e-4, 0.0, 0.0, 0.0, 7.6e-4, 0.0, 0.0, 0.0, 7.6e-4]

  drive_controller:
    ros__parameters:
      left_wheel_names: [fl_wheel_joint, rl_wheel_joint]
      right_wheel_names: [fr_wheel_joint, rr_wheel_joint]

      wheel_separation: 0.616
      wheel_radius: 0.1016

      # TODO: check it
      # For skid drive kinematics it will act as ICR coefficient, kinematic model with ICR
      # coefficient isn't totally accurate and this coefficient can differ for various ground types
      wheel_separation_multiplier: 1.0

      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0

      publish_rate: 100.0
      odom_frame_id: odom
      base_frame_id: base_link
      twist_covariance_diagonal: [2.7e-5, 2.7e-5, 0.0, 0.0, 0.0, 1.0e-4] # Selected intuitively based on WH01 results

      # Whether to use feedback or commands for odometry calculations
      open_loop: false

      # Update odometry from velocity
      # in sensor fusion only velocity is used and with this setting it is more accurate
      position_feedback: false
      # velocity computation filtering
      velocity_rolling_window_size: 1

      enable_odom_tf: false

      cmd_vel_timeout: 0.2
      publish_limited_velocity: false

      # Velocity and acceleration limits
      linear:
        x:
          max_velocity: 1.1 # m/s
          min_velocity: -1.1 # m/s
          max_acceleration: 1.5 # m/s^2
          max_deceleration: -1.5 # m/s^2
          max_acceleration_reverse: -1.5 # m/s^2
          max_deceleration_reverse: 1.5 # m/s^2
          max_jerk: .NAN # m/s^3
          min_jerk: .NAN # m/s^3

      angular:
        z:
          max_velocity: 2.2 # rad/s
          min_velocity: -2.2 # rad/s
          max_acceleration: 3.2 # rad/s^2
          max_deceleration: -3.2 # rad/s^2
          max_acceleration_reverse: -3.2 # rad/s^2
          max_deceleration_reverse: 3.2 # rad/s^2
          max_jerk: .NAN # rad/s^3
          min_jerk: .NAN # rad/s^3
