# For detailed information on configuring the parameter_bridge, please refer to:
# https://github.com/gazebosim/ros_gz/tree/ros2/ros_gz_bridge#example-5-configuring-the-bridge-via-yaml

- ros_topic_name: /<namespace>/battery/battery_status
  gz_topic_name: /model/<model_name>/battery/<namespace>/battery/state
  ros_type_name: sensor_msgs/msg/BatteryState
  gz_type_name: gz.msgs.BatteryState
  direction: GZ_TO_ROS

- topic_name: /<namespace>/cmd_vel
  ros_type_name: geometry_msgs/msg/TwistStamped
  gz_type_name: gz.msgs.Twist
  direction: GZ_TO_ROS

- topic_name: /<namespace>/lights/channel_1_frame
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: ROS_TO_GZ

- topic_name: /<namespace>/lights/channel_2_frame
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: ROS_TO_GZ
