# By default Husarion UGV is loaded without any components.

components: []

# If you want to add for example DEV02, LDR06 and CAM01 to your robot look at the example below:

# components:
#   - type: DEV02

#   - type: LDR06
#     parent_link: mount_link
#     xyz: 0.0 -0.1 0.0
#     rpy: 0.0 0.0 0.0
#     device_namespace: second_lidar

#   - type: CAM01
#     name: camera
#     parent_link: mount_link
#     xyz: 0.1 0.0 0.0
#     rpy: 0.0 0.0 0.0
#     device_namespace: front_cam
