wheel_radius: 0.1825
wheel_width: 0.14
mount_point_offset: 0.091
mass: 3.0
inertia: { ixx: 0.022510, iyy: 0.034850, izz: 0.022510 }
inertia_y_offset: 0.0
mesh_package: husarion_ugv_description
folder_path: meshes/WH01
mecanum: False
