---
name: Backport

on:
  pull_request_target:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull request number to backport. Please add backport labels to the PR before running
          this workflow.
        required: true

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_dispatch') ||
      (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.merged
      )
    steps:
      - uses: actions/checkout@v4
      - uses: korthout/backport-action@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          source_pr_number: ${{ inputs.pr_number || github.event.pull_request.number }}
